Repository prgrms-web-devcourse/Team_DAYZ_DAYZ_FE, pull requests merged in 2021-12, with the labels that each got.

#10 #3 클래스 디테일 페이지 마크업, 모달창 구현
  src/components/base/Modal/index.tsx
  src/components/index.tsx
  src/hooks/index.tsx
  src/hooks/useClickAway.tsx
  src/pages/ClassDetailPage/ReviewModal.tsx
  src/pages/ClassDetailPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
  src/utils/constants/apiConstant.js
Labels: feat

#11 #9 HomePage 구현
  src/pages/Category/Pottery.tsx
  src/pages/HomePage.tsx
  src/routes/Router.tsx
Labels: feat

#16 #12 Feed 화면 구현
  src/pages/FeedPage.tsx
  src/routes/Router.tsx
  src/template/Navigator/Navigator.tsx
Labels: feat

#18 #15 Resetcss, defaultTemplate 크기 설정
  src/App.tsx
  src/reset.tsx
  src/template/DefaultTemplate.tsx
  src/template/Navigator/Navigator.tsx
  tsconfig.json
Labels: feat, design

#20 #19 라우팅, 변수명 변경
  src/pages/AuthorPage/AuthorPage.tsx
  src/pages/CategoryPage/Pottery.tsx
  src/pages/ChangeLocation.tsx
  src/pages/ExplorePage.tsx
  src/pages/FeedPage/FeedPage.tsx
  src/pages/LoginPage/LoginHome.tsx
  src/pages/LoginPage/SignupAuthorInfo.tsx
  src/pages/LoginPage/SignupCheckLocation.tsx
  src/pages/LoginPage/SignupHome.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/ProductsDetailPage/ReviewModal.tsx
  src/pages/ProductsDetailPage/index.tsx
  src/pages/ReservationPage/ReservationPage.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/UserPage/UserPage.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
Labels: feat

#23 #22 Route 폴더 구조 변경
  package.json
  src/pages/AuthorPage/index.tsx
  src/pages/CategoryPage/Pottery.tsx
  src/pages/CategoryPage/index.tsx
  src/pages/FeedPage/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/NotFoundPage/index.tsx
  src/pages/ProductsDetailPage/index.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/UserPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: style

#26 #25 SearchPage구현
  src/pages/Comments/Comments.tsx
  src/pages/Comments/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
  src/template/Navigator/Navigator.tsx
Labels: feat, design

#30 #24 로그인, 회원가입 스타일링
  src/pages/LoginPage/SignupAuthorInfo.tsx
  src/pages/LoginPage/SignupCheckLocation.tsx
  src/pages/LoginPage/SignupHome.tsx
  src/pages/LoginPage/index.tsx
  src/routes/Router.tsx
  src/template/DefaultTemplate.tsx
Labels: design

#28 #14 datepicker 적용
  package.json
  src/components/base/Modal/index.tsx
  src/pages/BookingPage/calendar.css
  src/pages/BookingPage/index.tsx
  src/pages/ProductsDetailPage/index.tsx
  src/pages/ReservationPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: feat

#29 #27 검색 결과 페이지 구현
  src/pages/SearchPage/index.tsx
  src/pages/SearchResultsPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
  src/template/Header/Header.tsx
  src/template/Navigator/Navigator.tsx
Labels: feat, design

#33 #32 업로드 페이지 구현
  src/components/base/Upload/index.tsx
  src/components/base/index.tsx
  src/components/index.tsx
  src/hooks/index.tsx
  src/hooks/useClickAway.ts
  src/hooks/useForm.ts
  src/pages/ProductsDetailPage/index.tsx
  src/pages/UploadFeedPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
Labels: feat

#35 #34 전반적인 레이아웃 수정
  src/pages/FeedPage/index.tsx
  src/pages/HomePage/index.tsx
  src/template/DefaultTemplate.tsx
  src/template/Header/Header.tsx
  src/template/Navigator/Navigator.tsx
Labels: style, design

#39 #37 UserPage 구현
  src/pages/UserPage/index.tsx
  src/template/Navigator/Navigator.tsx
Labels: feat, design

#36 #31 카테고리 페이지 구현
  src/pages/CategoryPage/index.tsx
  src/pages/Comments/index.tsx
Labels: feat, design

#41 #40 UserPage 예약내역 페이지 구현
  src/pages/UserPage/UserBookedPage.tsx
  src/pages/UserPage/UserPage.tsx
  src/pages/UserPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
Labels: feat, design

#44 #38 Workshop 페이지 디자인 및 라우팅 구현
  src/pages/AuthorPage/index.tsx
  src/pages/WorkshopPage/FeedList.tsx
  src/pages/WorkshopPage/ProductsList.tsx
  src/pages/WorkshopPage/ReviewList.tsx
  src/pages/WorkshopPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
Labels: feat

#49 #48 프로필 수정 페이지 구현
  src/pages/UserPage/UserPage.tsx
  src/pages/UserPage/UserProfileEditPage.tsx
  src/pages/UserPage/index.tsx
  src/routes/Router.tsx
Labels: feat, design

#51 #50 전반적인 라우팅처리와 Design수정
  src/pages/HomePage/index.tsx
  src/pages/WorkshopPage/index.tsx
Labels: design

#45 #43 Feat : 팔로잉 페이지 구현
  src/pages/UserPage/UserFollowingPage.tsx
  src/pages/UserPage/UserPage.tsx
  src/pages/UserPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
Labels: feat, design

#47 #46 User 후기 모아보기 페이지 생성
  src/pages/UserPage/UserPage.tsx
  src/pages/UserPage/UserReviewPage.tsx
  src/pages/UserPage/index.tsx
  src/routes/Router.tsx
Labels: feat, design

#53 #42 리뷰 남기기 페이지 구현, 버튼 컴포넌트 구현
  src/components/base/Button/index.tsx
  src/components/base/Image/index.tsx
  src/components/base/Text/index.tsx
  src/components/base/index.tsx
  src/pages/LeaveCommentPage/index.tsx
  src/pages/UserPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
  src/template/DefaultTemplate.tsx
  src/template/Header/Header.tsx
  src/template/Navigator/Navigator.tsx
Labels: feat

#59 #55 Product 새로 추가하기 페이지 구현
  package.json
  src/components/base/Upload/index.tsx
  src/pages/UploadProductPage/calendar.css
  src/pages/UploadProductPage/index.tsx
  src/pages/UserPage/index.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: feat, design

#57 #56 themeProvider 적용
  src/App.tsx
  src/style/index.tsx
  src/style/reset.tsx
  src/style/theme.ts
  src/types/emotion.d.ts
Labels: feat

#60 #54 돌아가기 컴포넌트, 아바타 컴포넌트 구현
  src/components/base/Avatar/index.tsx
  src/components/base/Image/index.tsx
  src/components/domain/Goback/index.tsx
  src/components/domain/index.tsx
  src/pages/UserPage/UserPage.tsx
Labels: feat, style

#63 #61 Scroll 수정 및 feed Img 크기 수정
  src/pages/CategoryPage/index.tsx
  src/pages/Comments/index.tsx
  src/pages/FeedPage/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SearchResultsPage/index.tsx
  src/pages/UserPage/UserPage.tsx
Labels: design

#66 #64 이미지 미리보기 구현
  src/components/base/Upload/index.tsx
  src/pages/UploadProductPage/index.tsx
Labels: feat, design

#69 #65 별점 라이브러리 적용, 라우트 도메인 변경
  package.json
  src/pages/CommentsPage/index.tsx
  src/pages/UploadCommentPage/index.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
  yarn.lock
Labels: feat

#71 #67 Homepage 이모티콘 수정
  package.json
  src/pages/HomePage/index.tsx
  src/template/Navigator/Navigator.tsx
  yarn.lock
Labels: design, refactor

#73 #72 date 선택후 추가시 선택한 date들을 list 로 보여줌
  src/pages/UploadProductPage/index.tsx
Labels: feat

#76 #70 productsDetail 도메인 구현, 디자인 변경
  src/components/base/Avatar/index.tsx
  src/components/base/Image/index.tsx
  src/components/base/Modal/index.tsx
  src/components/base/index.tsx
  src/components/domain/AteliarInformation/index.tsx
  src/components/domain/SimpleReview/index.tsx
  src/components/domain/index.tsx
  src/pages/ProductsDetailPage/index.tsx
Labels: feat, design, refactor

#79 #77 모달 디자인 변경, 도메인화, theme 적용
  src/components/domain/Review/index.tsx
  src/components/domain/index.tsx
  src/pages/ProductsDetailPage/ReviewModal.tsx
  src/pages/ProductsDetailPage/index.tsx
  src/style/theme.ts
Labels: feat, design, refactor

#85 #81 Toast 컴포넌트 구현
  src/components/base/Toast/ToastItem.tsx
  src/components/base/Toast/ToastManager.tsx
  src/components/base/Toast/index.tsx
  src/components/base/index.tsx
  src/hooks/index.tsx
  src/hooks/useTimeout.ts
  src/hooks/useTimeoutFn.ts
Labels: feat

#78 #74 지역 선택 모달창 구현
  src/components/base/Modal/index.tsx
  src/components/domain/LocationSetting/index.tsx
  src/components/domain/index.tsx
  src/hooks/useToggle.ts
  src/template/Header/Header.tsx
Labels: feat

#84 #75 workshop setting, edit page 스타일링
  src/components/base/index.tsx
  src/components/domain/LinkBox/index.tsx
  src/components/domain/index.tsx
  src/pages/WorkshopPage/EditPage.tsx
  src/pages/WorkshopPage/FeedListPage.tsx
  src/pages/WorkshopPage/ProductsList.tsx
  src/pages/WorkshopPage/ProductsListPage.tsx
  src/pages/WorkshopPage/ReviewListPage.tsx
  src/pages/WorkshopPage/SettingPage.tsx
  src/pages/WorkshopPage/WorkshopHeader.tsx
  src/pages/WorkshopPage/WorkshopPage.tsx
  src/pages/WorkshopPage/index.tsx
  src/pages/index.tsx
Labels: feat, design, refactor

#83 #82 날짜 선택 추가/ 삭제 및 datepicker 스타일 변경
  src/pages/UploadProductPage/calendar.css
  src/pages/UploadProductPage/index.tsx
  src/routes/Router.tsx
  src/template/Navigator/Navigator.tsx
Labels: feat, refactor

#88 Feat: redirects 추가
  public/_redirects
Labels: feat

#92 #90 로그인 페이지, 유저 페이지 스타일 리펙토링
  src/components/base/Input/index.tsx
  src/components/domain/index.tsx
  src/pages/LoginPage/SignupAuthorInfo.tsx
  src/pages/LoginPage/SignupCheckLocation.tsx
  src/pages/LoginPage/index.tsx
  src/pages/UserPage/UserPage.tsx
  src/pages/UserPage/UserProfileEditPage.tsx
  src/pages/WorkshopPage/EditPage.tsx
  src/template/DefaultTemplate.tsx
Labels: design, refactor

#93 #86 예약하기 페이지 구현
  src/components/domain/Goback/index.tsx
  src/pages/BookingPage/calendar.css
  src/pages/BookingPage/index.tsx
  src/pages/ProductsDetailPage/index.tsx
  src/pages/UploadProductPage/index.tsx
  src/style/calendar.css
Labels: feat, design

#95 #91 datepick refactor
  src/components/domain/LocationSetting/index.tsx
  src/pages/SearchResultsPage/index.tsx
  src/pages/UploadProductPage/index.tsx
  src/style/calendar.css
Labels: feat, refactor

#97 #94 API 기본 세팅
  package.json
  src/components/domain/Goback/index.tsx
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
  src/utils/constants/apiConstant.ts
  yarn.lock
Labels: feat

#100 #98 검색페이지, 검색결과 조회 리팩토링 더미데이터 생성
  src/components/base/Avatar/index.tsx
  src/components/domain/Goback/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SearchResultsPage/DUMMY_DATA.ts
  src/pages/SearchResultsPage/index.tsx
Labels: feat, refactor

#103 #101 요청한 지역 설정 정보를 초기값으로 보여주는 처리
  src/components/domain/Goback/index.tsx
  src/components/domain/LocationSetting/index.tsx
  src/pages/CommentsPage/index.tsx
Labels: feat

#104 #102 리팩토링, 더미데이터 추가, Icon 분리
  src/pages/HomePage/DUMMY_DATA.ts
  src/pages/HomePage/categoryIcons.ts
  src/pages/HomePage/index.tsx
Labels: design, refactor

#99 #96 workshop page dummy data 붙여서page 수정
  src/components/base/Upload/index.tsx
  src/pages/FeedPage/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/UploadProductPage/index.tsx
  src/pages/WorkshopPage/FeedListPage.tsx
  src/pages/WorkshopPage/ProductsListPage.tsx
  src/pages/WorkshopPage/ReviewListPage.tsx
  src/pages/WorkshopPage/SettingPage.tsx
  src/pages/WorkshopPage/WorkshopHeader.tsx
  src/pages/WorkshopPage/index.tsx
  src/routes/Router.tsx
  src/template/Header/Header.tsx
Labels: feat

#108 Fix: 3개였던 관심지역을 하나로 줄임
  src/components/domain/LocationSetting/index.tsx
  src/pages/HomePage/index.tsx
  src/template/Header/Header.tsx
Labels: refactor

#110 #109 userpage 예약 내역 및 후기 남기기 page dummy data 붙임
  src/pages/UploadCommentPage/index.tsx
  src/pages/UserPage/UserBookedPage.tsx
  src/routes/Router.tsx
Labels: feat, design, refactor

#112 #106 더미데이터 추가, 디자인 변경
  src/pages/WorkshopPage/DUMMY_DATA.ts
  src/pages/WorkshopPage/FeedListPage.tsx
  src/pages/WorkshopPage/ProductsListPage.tsx
  src/pages/WorkshopPage/ReviewListPage.tsx
  src/pages/WorkshopPage/WorkshopHeader.tsx
  src/pages/WorkshopPage/WorkshopPage.tsx
Labels: feat, design, refactor

#117 #115 routePath에 공방 id 누락 수정
  src/pages/WorkshopPage/SettingPage.tsx
  src/pages/WorkshopPage/WorkshopHeader.tsx
  src/pages/WorkshopPage/WorkshopPage.tsx
  src/pages/WorkshopPage/index.tsx
Labels: fix

#116 # 113 feedpage & commentpage dummydata 붙임
  package.json
  src/pages/CommentsPage/index.tsx
  src/pages/FeedPage/flicker.css
  src/pages/FeedPage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/UploadCommentPage/index.tsx
  src/pages/UserPage/UserBookedPage.tsx
  src/pages/UserPage/UserProfileEditPage.tsx
  src/template/Navigator/Navigator.tsx
  yarn.lock
Labels: feat

#118 #114 classDetailPage 더미데이터 붙힘, 디자인 수정
  src/components/domain/AteliarInformation/index.tsx
  src/pages/HomePage/index.tsx
  src/pages/ProductsDetailPage/DUMMY_DATA.ts
  src/pages/ProductsDetailPage/index.tsx
Labels: feat, design

#120 #119 privateRoute 구현, sessionStorage 함수 구현
  src/routes/PrivateRoute/index.tsx
  src/utils/functions/index.ts
  src/utils/functions/sessionStorage.ts
Labels: feat

#121 #105 recoil로 userState 저장
  src/atom.ts
  src/index.tsx
  src/pages/LoginPage/index.tsx
Labels: feat

#124 #122 class detail page flicking 도입
  src/components/domain/SimpleReview/index.tsx
  src/pages/CategoryPage/index.tsx
  src/pages/FeedPage/index.tsx
  src/pages/ProductsDetailPage/DUMMY_DATA.ts
  src/pages/ProductsDetailPage/flicker.css
  src/pages/ProductsDetailPage/index.tsx
Labels: feat

#125 #123 design, react-hook-form 적용
  package.json
  src/pages/UploadFeedPage/index.tsx
  src/pages/UploadProductPage/index.tsx
  yarn.lock
Labels: feat, design

#128 #127 class detail page& review modale 별점 추가 / productupload page 날짜 선택 디자인 변화
  src/components/domain/Review/index.tsx
  src/pages/ProductsDetailPage/ReviewModal.tsx
  src/pages/ProductsDetailPage/index.tsx
  src/pages/UploadProductPage/index.tsx
Labels: design, refactor

#130 #111 공방 프로필 페이지 수정
  src/components/base/Input/index.tsx
  src/pages/UserPage/UserProfileEditPage.tsx
  src/pages/WorkshopPage/EditPage.tsx
  src/pages/WorkshopPage/WorkshopPage.tsx
Labels: feat

#132 #129 별점 컴포넌트 제작
  src/components/base/Rating/index.tsx
  src/components/base/index.tsx
  src/pages/UploadCommentPage/index.tsx
Labels: feat

#131 #126 UploadProductPage react-hook-form 적용
  src/constants/apiConstant.ts
  src/constants/categoryItems.ts
  src/pages/HomePage/index.tsx
  src/pages/UploadProductPage/index.tsx
  src/pages/UploadProductPage/types.ts
  src/utils/api/dayzApi.ts
Labels: feat, design, refactor

#136 #133 이미지 업로드 api 적용, 미리보기 적용
  package.json
  src/components/domain/CustomImageUpload/index.tsx
  src/components/domain/index.tsx
  src/pages/UploadCommentPage/index.tsx
  src/pages/UploadFeedPage/index.tsx
  src/pages/UploadProductPage/index.tsx
  src/pages/UploadProductPage/types.ts
  src/utils/api/dayzApi.ts
  yarn.lock
Labels: feat, refactor

#137 #135 관심지역 설정 api 붙임
  src/atom.ts
  src/components/domain/LocationSetting/index.tsx
  src/template/Header/Header.tsx
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
Labels: feat

#140 #138 관심지역 변경(설정과 동일) api 통신 하다가 중단
  src/atom.ts
  src/components/domain/LocationSetting/index.tsx
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
Labels: refactor

#141 #134 카카오 로그인 구현
  src/atom.ts
  src/components/base/Input/OfficeHourInput.tsx
  src/components/base/Input/PhoneNumInput.tsx
  src/components/base/index.tsx
  src/components/domain/LocationSetting/index.tsx
  src/pages/LoginPage/RedirectPageAfterKakao.tsx
  src/pages/LoginPage/SignupAuthorInfo.tsx
  src/pages/LoginPage/SignupCheckLocation.tsx
  src/pages/LoginPage/index.tsx
  src/pages/WorkshopPage/EditPage.tsx
  src/pages/index.tsx
  src/routes/Router.tsx
  src/template/DefaultTemplate.tsx
  src/utils/api/dayzApi.ts
Labels: feat

#143 #139 recoil을 이용한 nav 제어, UploadProuducts페이지 리팩토링
  src/atoms/index.ts
  src/atoms/navigation.ts
  src/atoms/types.ts
  src/atoms/user.ts
  src/components/domain/BookingTable/index.tsx
  src/components/domain/CustomImageUpload/index.tsx
  src/components/domain/ErrorMessage/index.tsx
  src/components/domain/LocationSetting/index.tsx
  src/components/domain/index.tsx
  src/pages/CategoryPage/index.tsx
  src/pages/LoginPage/RedirectPageAfterKakao.tsx
  src/pages/LoginPage/SignupCheckLocation.tsx
  src/pages/UploadCommentPage/index.tsx
  src/pages/UploadFeedPage/index.tsx
  src/pages/UploadProductPage/index.tsx
  src/pages/UploadProductPage/types.ts
  src/template/DefaultTemplate.tsx
  src/template/Header/Header.tsx
  src/template/Navigator/Navigator.tsx
  src/utils/functions/convertFullDate.ts
  src/utils/functions/index.ts
Labels: feat, style, refactor

#146 #144 api 형식에 맞도록 데이터 수정
  src/atoms/user.ts
  src/components/domain/CustomImageUpload/index.tsx
  src/components/domain/ErrorMessage/index.tsx
  src/constants/categoryItems.ts
  src/pages/UploadCommentPage/index.tsx
  src/pages/UploadFeedPage/index.tsx
  src/pages/UploadProductPage/index.tsx
  src/pages/UploadProductPage/types.ts
  src/types/ImageType.ts
  src/types/index.ts
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
  src/utils/functions/convertDate.ts
  src/utils/functions/convertImageArray.ts
  src/utils/functions/index.ts
Labels: feat, refactor

#147 #145 관심지역 설정 POST 요청 수정, btn ui 컴포넌트 이벤트 받게 하기, location-check에 submitBnt 적용
  src/components/base/Button/index.tsx
  src/pages/LoginPage/SignupCheckLocation.tsx
Labels: fix

#151 #148 모달(지역선택) on off 추가, pages 폴더 정렬
  src/atoms/index.ts
  src/atoms/modal.ts
  src/atoms/types.ts
  src/atoms/user.ts
  src/components/domain/BookingTable/index.tsx
  src/components/domain/CustomImageUpload/index.tsx
  src/pages/booking/BookingPage.tsx
  src/pages/booking/index.tsx
  src/pages/category/CategoryPage.tsx
  src/pages/category/index.tsx
  src/pages/comments/CommentsPage.tsx
  src/pages/comments/index.tsx
  src/pages/feed/FeedPage.tsx
  src/pages/feed/flicker.css
  src/pages/feed/index.tsx
  src/pages/home/DUMMY_DATA.ts
  src/pages/home/HomePage.tsx
  src/pages/home/index.tsx
  src/pages/index.tsx
  src/pages/notFound/NotFoundPage.tsx
  src/pages/notFound/index.tsx
  src/pages/products/DUMMY_DATA.ts
  src/pages/products/ProductsDetailPage.tsx
  src/pages/products/ReviewModal.tsx
  src/pages/products/flicker.css
  src/pages/products/index.tsx
  src/pages/search/DUMMY_DATA.ts
  src/pages/search/SearchPage.tsx
  src/pages/search/SearchResultsPage.tsx
  src/pages/search/index.tsx
  src/pages/upload/UploadCommentPage.tsx
  src/pages/upload/UploadFeedPage.tsx
  src/pages/upload/UploadProductPage.tsx
  src/pages/upload/index.tsx
  src/pages/user/UserBookedPage.tsx
  src/pages/user/UserFollowingPage.tsx
  src/pages/user/UserPage.tsx
  src/pages/user/UserProfileEditPage.tsx
  src/pages/user/UserReviewPage.tsx
  src/pages/user/index.tsx
  src/template/Header/Header.tsx
  src/types/DataTypes.ts
  src/types/index.ts
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
Labels: feat, refactor

#157 #150 관심지역 설정 후 화면 새로 돌아 가게 설정
  src/components/domain/LocationSetting/index.tsx
  src/pages/search/SearchPage.tsx
  src/pages/upload/UploadProductPage.tsx
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
Labels: feat

#153 #152 지역구 선택 recoil로 불러오기 기능 추가
  src/App.tsx
  src/atoms/index.ts
  src/atoms/modal.ts
  src/atoms/user.ts
  src/components/domain/LocationSetting/index.tsx
  src/pages/category/CategoryPage.tsx
  src/pages/products/ProductsDetailPage.tsx
  src/pages/upload/UploadProductPage.tsx
  src/template/DefaultTemplate.tsx
  src/template/Header/Header.tsx
  src/template/Header/index.tsx
  src/template/Navigator/Navigator.tsx
  src/template/Navigator/index.tsx
  src/types/DataTypes.ts
  src/types/index.ts
  src/utils/api/dayzApi.ts
Labels: feat

#155 #154 유효한 사용자인지 check, privateRoute 재설정
  src/atoms/index.ts
  src/atoms/user.ts
  src/constants/sessionStorage.ts
  src/routes/CustomRoutes/PrivateRoute.tsx
  src/routes/CustomRoutes/index.tsx
  src/routes/PrivateRoute/index.tsx
  src/template/DefaultTemplate.tsx
  src/utils/api/dayzApi.ts
  src/utils/functions/sessionStorage.ts
Labels: feat

#159 #156 link 위치 변경, atom 토큰 변경, 주석제거
  src/atoms/user.ts
  src/components/domain/Goback/index.tsx
  src/pages/comments/CommentsPage.tsx
  src/pages/feed/FeedPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/products/ProductsDetailPage.tsx
  src/pages/products/flicker.css
  src/style/flicker.css
Labels: design, refactor

#162 #161 결제 성공 페이지 추가, state 넘겨주기
  src/atoms/modal.ts
  src/components/base/Button/index.tsx
  src/components/domain/LocationSetting/index.tsx
  src/pages/booking/BookingPage.tsx
  src/pages/booking/DUMMY_DATA.ts
  src/pages/booking/SuccessBookPage.tsx
  src/pages/booking/index.tsx
  src/pages/category/CategoryPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/index.tsx
  src/pages/search/SearchPage.tsx
  src/routes/Router.tsx
Labels: feat, design, refactor

#163 #142 일반유저 로그인 (WIP)
  .vscode/launch.json
  src/atoms/user.ts
  src/components/base/Input/OfficeHourInput.tsx
  src/components/base/Input/PhoneNumInput.tsx
  src/components/base/Input/index.tsx
  src/components/base/index.tsx
  src/components/domain/LoginLocationGetter/index.tsx
  src/components/domain/index.tsx
  src/pages/LoginPage/RedirectPageAfterKakao.tsx
  src/pages/LoginPage/SignupAuthorInfo.tsx
  src/pages/LoginPage/SignupCheckLocation.tsx
  src/pages/LoginPage/index.tsx
  src/pages/WorkshopPage/DUMMY_DATA.ts
  src/pages/WorkshopPage/EditPage.tsx
  src/pages/home/HomePage.tsx
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
Labels: feat

#165 #164 로그인 구현
  src/atoms/user.ts
  src/constants/sessionStorage.ts
  src/pages/LoginPage/RedirectPageAfterKakao.tsx
  src/pages/LoginPage/index.tsx
  src/pages/home/HomePage.tsx
  src/routes/CustomRoutes/PrivateRoute.tsx
  src/routes/Router.tsx
  src/template/DefaultTemplate.tsx
  src/utils/api/dayzApi.ts
  src/utils/functions/sessionStorage.ts
Labels: feat

#166 #158 홈페이지 api
  .prettierrc.json
  src/atoms/user.ts
  src/pages/home/HomePage.tsx
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
Labels: feat

#168 #160 메인페이지, 카테고리 페이지 api 연동
  src/atoms/modal.ts
  src/atoms/user.ts
  src/pages/WorkshopPage/DUMMY_DATA.ts
  src/pages/WorkshopPage/ProductsListPage.tsx
  src/pages/WorkshopPage/ReviewListPage.tsx
  src/pages/booking/BookingPage.tsx
  src/pages/booking/SuccessBookPage.tsx
  src/pages/category/CategoryPage.tsx
  src/pages/feed/FeedPage.tsx
  src/pages/home/DUMMY_DATA.ts
  src/pages/home/HomePage.tsx
  src/pages/products/ProductsDetailPage.tsx
  src/pages/upload/UploadFeedPage.tsx
  src/pages/upload/UploadProductPage.tsx
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
Labels: feat, design

#170 #169 예약 api 수정, 예약 api 조회 구현
  src/pages/booking/BookingPage.tsx
  src/pages/user/UserBookedPage.tsx
  src/utils/api/dayzApi.ts
Labels: feat, refactor

#172 #171 favicon 추가
  public/favicon.ico
  public/index.html
Labels: design

#175 #167 id에 따른 상세페이지 보여주기
  src/components/domain/AteliarInformation/index.tsx
  src/components/domain/Goback/index.tsx
  src/pages/WorkshopPage/DUMMY_DATA.ts
  src/pages/WorkshopPage/WorkshopHeader.tsx
  src/pages/category/CategoryPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/products/ProductsDetailPage.tsx
  src/pages/user/UserPage.tsx
  src/routes/CustomRoutes/PrivateRoute.tsx
  src/routes/Router.tsx
  src/template/Navigator/index.tsx
  src/utils/api/dayzApi.ts
Labels: feat

#177 #176 상세페이지 후기 api 연동
  package.json
  src/components/domain/Review/index.tsx
  src/pages/booking/BookingPage.tsx
  src/pages/category/CategoryPage.tsx
  src/pages/products/DUMMY_DATA.ts
  src/pages/products/ProductsDetailPage.tsx
  src/pages/products/ReviewModal.tsx
  src/pages/upload/UploadProductPage.tsx
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
  yarn.lock
Labels: feat

#180 #178 피드페이지 api 연동
  src/pages/WorkshopPage/DUMMY_DATA.ts
  src/pages/WorkshopPage/ProductsListPage.tsx
  src/pages/WorkshopPage/ReviewListPage.tsx
  src/pages/WorkshopPage/WorkshopHeader.tsx
  src/pages/feed/FeedPage.tsx
  src/pages/home/HomePage.tsx
  src/pages/user/UserBookedPage.tsx
  src/utils/api/dayzApi.ts
  src/utils/api/types.ts
Labels: feat

#182 Fix: 공방 클래스 등록 후 페이지 이동 처리
  Dayz.postman_collection.json
  src/pages/upload/UploadProductPage.tsx
Labels: fix

#185 HotFix: redirect after kakao 오타수정
  src/pages/LoginPage/index.tsx
Labels: fix
